### ISSUE TITLE
Security Implecations

### ISSUE THREAD

**Issue by Muvkina** [sdsddsd1/mywayland#2]
Is there any security concerns for this over rootless xorg? Also is it possible to use other wlroots wms?

**Comment by dylanaraps** [comment]
Well, there are three different ways to run sway without the need for `root`. The recommended and "safest" method is to run it through (e)logind. The next method is to give the sway binary `suid` permissions (you typically want to avoid this). The last method is to give the swap binary capabilities via `libcap` and its utilities.

This repository uses the capabilities method (last listed). You can see what this entails here: https://github.com/sdsddsd1/mywayland/commit/347c79997c38b355488029583ef41bd7004fd734 Now, the one issue with the capabilities method is that sway **will not** drop the capabilities it is given (so, thought must go into which capabilities it is granted. The less the better).

The suid method while usually avoided is probably safer than the capabilities method in use now. Sway will detect that it is suid and **drop** all permissions/root once unneeded.  

The final and untested method is to do what we do for Xorg. Give it `guid` `input` so **only** the Xorg binary has access to `/dev/input` (any children do not). There are then patches related to DRM_MASTER which are used to control a TTY without root (on a single-seat system of course).

Regardless, so long as the capabilities aren't too grand and we set as little as possible, you should be 100% fine. A simple patch could also be written for sway which would make it drop its capabilities the moment they're unneeded.

Lots of options to choose from here. I guess the most important thing is to solidify **the defaults**. Which solution works best in the most cases. Of course, I have no say in this repository! It's up to @sdsddsd1 to either swap methods, modify the existing one or change things entirely. :)

**Comment by sdsddsd1** [comment]
First of all I must admit I have just packaged this and everything about writing my own patch
goes above my head. But I would like to make this a viable and SANE option, because
firefox vaapi and 1+ smooth scrolling kicks ass.  
I have no personal preference how to improve the situation, I would just follow rationality.
So yeah testing and pullrequests welcome :+1:   
Thanks for heads up!  
Going after [sway wiki](https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd),  
I have allready ditched the requirement for user to be in input group by setting setgid input on sway.
I have tested this with video aswell but no sucess.  
  
  
For other wlroots windowmanagers: I have sucessfully tested cage and hikari.

**Comment by sdsddsd1** [comment]
### I could clear things up for me and come to the temporarily conclusion:
I want to avoid elogind or equivalent for complexity reasons when possible and sane.
Void and alpine distribute sway by default with suid(`chmod u+s`). Void offers elogind as an option.
So it cant be _that_ insane.
The only beneficial I see for the `SYS_CAP` capabilities method that it looks like a user process on the outside but on the down side of things it has a `root backdoor all the time`. So its more a cosmetic option?
I haven´t found another suiting capability on the fast look. I will investigate more on this topic.

SUID seems _ok_ for sway but that must not be true for other wlroots based compositors.

I have found this interesting [read](https://www.reddit.com/r/voidlinux/comments/e8x4c1/whats_the_point_of_elogind/) on /r/voidlinux.

Edit: I opened an issue regarding `dropping capability` at sway´s repo. [link](https://github.com/swaywm/sway/issues/5260)
Edit2: Ok libcap should not be used. See above link.

**Comment by sdsddsd1** [comment]
There might be more outrageous monsters out there. Closed.
