### ISSUE TITLE
[TIP] dmenu-wayland

### ISSUE THREAD

**Issue by ngortheone** [sdsddsd1/mywayland#4]
Way better than bemenu

https://github.com/nyyManni/dmenu-wayland

**Comment by sdsddsd1** [comment]
I have a launcher just for convenience in this repo since I personally use a terminal for starting stuff.
Thanks anyway!  
Do you know this resource? [link](https://github.com/natpen/awesome-wayland)

**Comment by ngortheone** [comment]
I did not! Thanks!

Feel free to close this one if you think it represents no value.
